### ISSUE TITLE
Tracking Issue : Interface Homme Machine

### ISSUE THREAD

**Issue by TLBail** [TLBail/biotrace#8]
Tracking issue pour les différentes interfaces:
le développement pourra commencer dès que les maquettes auront été terminé. #1  

- [x] Structure du site (Menu avec les différentes routes)
- [x] Test communication avec un automate
- [x] Sauvegarde des fichiers de configuration de la webdyn
- [x] Suivi de logs
- [x] Pont bascule
- [ ] Emulation de la webdyn
- [x] Configuration général
